using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
namespace UsageDock.App;
public sealed class Widget : Window
{
 private string? themeError;
 internal void SetThemeError(string? message){themeError=message;Repaint();}
 private readonly DockController controller;private readonly Dashboard dashboard;
 public Widget(DockController controller,Dashboard dashboard){this.controller=controller;this.dashboard=dashboard;Ui.Window(this,Ui.L("UsageDock · Mini widget"),268,548);MinWidth=268;MinHeight=300;Topmost=true;Design.Chrome(this);controller.Changed+=Repaint;Ui.PaletteChanged+=Repaint;Localization.Changed+=Repaint;Closed+=(_,_)=>{controller.Changed-=Repaint;Ui.PaletteChanged-=Repaint;Localization.Changed-=Repaint;};Repaint();}
 public void Repaint(){if(!Dispatcher.CheckAccess()){Dispatcher.Invoke(Repaint);return;}Title=Ui.L("UsageDock · Mini widget");Background=Ui.Background;var root=new Grid();root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(70)});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(68)});var h=Design.Canvas(266,70);h.Background=System.Windows.Media.Brushes.Transparent;Design.DragHeader(this,h);Design.At(h,Design.Icon("logo",22,Ui.Accent),18,20);Design.Txt(h,"UsageDock",48,21,16,null,true);Design.At(h,dashboard.ThemeButton("Theme.Toggle.Widget",true),146,15);Design.At(h,Design.Action("pin",Ui.L("Przełącz zawsze na wierzchu"),()=>{Topmost=!Topmost;Repaint();},28,30,false,true),180,15);Design.At(h,Design.Action("close",Ui.L("Zamknij widget"),Close,28,30,false,true),226,15);root.Children.Add(h);var cards=new StackPanel{Margin=new Thickness(18,0,12,0)};foreach(var a in controller.Accounts.Where(a=>a.Profile.IsFavorite))cards.Children.Add(dashboard.AccountCard(a,true));if(cards.Children.Count==0)cards.Children.Add(Ui.Label(Ui.L("Przypnij konta w panelu, aby zobaczyć je tutaj."),14,Ui.Muted));var scroll=new ScrollViewer{Content=cards,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};Grid.SetRow(scroll,1);root.Children.Add(scroll);var footer=Design.Canvas(266,68);if(themeError==null)Design.Txt(footer,Ui.L("Zawsze na wierzchu"),20,22,14,Ui.Muted);else Design.At(footer,new TextBlock{Text=Ui.L(themeError),Width=164,FontSize=12,TextWrapping=TextWrapping.Wrap,Foreground=Ui.Hex(Ui.Light?"#8A3E16":"#F7BA61")},20,14);var toggleCanvas=Design.Canvas(40,24);Design.At(toggleCanvas,new Border{Width=20,Height=20,CornerRadius=new CornerRadius(10),Background=Ui.Light?System.Windows.Media.Brushes.White:Ui.Text},Topmost?18:2,2);var toggle=new Button{Width=44,Height=28,Padding=new Thickness(0),Background=Topmost?Ui.Accent:Ui.Surface,Content=toggleCanvas,ToolTip=Ui.L("Zawsze na wierzchu")};toggle.Click+=(_,_)=>{Topmost=!Topmost;Repaint();};Design.At(footer,toggle,196,19);Grid.SetRow(footer,2);root.Children.Add(footer);Content=Design.Frame(root);}
}
